### ISSUE TITLE
Taking responsability of the client

### ISSUE THREAD

**Issue by SunkPlane29** [bradford-hamilton/godax#5]
I was taking another look at the code and saw that the client had a lot of responsibility like placing orders and listing products. So I created this pull request to discuss the possibility of letting the client having an order interface(maybe) and it accessing it to create orders, or get a specific order.

`type Orders interface {
    PlaceOrder(timestamp, signature string, req *http.Request)
    [...]
}

type Client struct {
    Orders Orders
    [...]
}
`

In this example, we would create an order interface with an underlying concrete type, but the client would just use the order interface so we can have a better dependency between the client and the orders and less responsibility in the client.

**Comment by bradford-hamilton** [comment]
Hey @SunkPlane29, thanks for opening an issue! I think at this point that would add unnecessary complexity and I'm not sure I understand what the enhancement would be. So I'm thinking we should pass on this one. Feel free to keep the ideas coming!
